---
- hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - vars.yml
  tasks:
  - cloudformation_facts:
      profile: '{{ aws_profile }}'
      region: us-east-2
      stack_name: static-ecs-cluster
  - ecs_service:
      profile: '{{ aws_profile }}'
      region: us-east-2
      state: present
      cluster: "{{ cloudformation['static-ecs-cluster'].stack_outputs.Cluster }}"
      name: ssh-targets-{{ item + 1 }}
      deployment_configuration:
        maximum_percent: 150
        minimum_healthy_percent: 10
      desired_count: 0
      task_definition: ssh-ansible-targets
      placement_strategy:
        - field: instanceId
          type: spread
    loop: '{{ range(10) | list }}'
  - ecs_service:
      profile: '{{ aws_profile }}'
      region: us-east-2
      state: present
      cluster: "{{ cloudformation['static-ecs-cluster'].stack_outputs.Cluster }}"
      name: cisco-ios-targets-{{ item + 1}}
      deployment_configuration:
        maximum_percent: 150
        minimum_healthy_percent: 10
      desired_count: 0
      task_definition: ios-ansible-targets
      placement_strategy:
        - field: instanceId
          type: spread
    loop: '{{ range(10) | list }}'
  - name: Scale instances down to zero
    cloudformation:
      template: ./cfn/ecs-static-size-cluster.yaml
      profile: '{{ aws_profile }}'
      region: us-east-2
      stack_name: static-ecs-cluster
      template_parameters:
        ParentVPCStack: scale-test-vpc
        SubnetsReach: Public
        InstanceType: c5.4xlarge
        SpotBidPrice: 0.20
        MaxSize: 8
        DesiredCapacity: 0
        MinSize: 0
        KeyName: '{{ key_name }}'
  - ecs_service:
      profile: '{{ aws_profile }}'
      region: us-east-2
      state: absent
      cluster: "{{ cloudformation['static-ecs-cluster'].stack_outputs.Cluster }}"
      name: ssh-targets-{{ item + 1 }}
      deployment_configuration:
        maximum_percent: 150
        minimum_healthy_percent: 10
      desired_count: 0
      task_definition: ssh-ansible-targets
      placement_strategy:
        - field: instanceId
          type: spread
    loop: '{{ range(10) | list }}'
  - ecs_service:
      profile: '{{ aws_profile }}'
      region: us-east-2
      state: absent
      cluster: "{{ cloudformation['static-ecs-cluster'].stack_outputs.Cluster }}"
      name: cisco-ios-targets-{{ item + 1}}
      deployment_configuration:
        maximum_percent: 150
        minimum_healthy_percent: 10
      desired_count: 0
      task_definition: ios-ansible-targets
      placement_strategy:
        - field: instanceId
          type: spread
    loop: '{{ range(10) | list }}'
  - ecs_taskdefinition:
      profile: '{{ aws_profile }}'
      region: us-east-2
      network_mode: bridge
      family: ssh-ansible-targets
      state: absent
      containers:
      - name: ssh-target
        image: '{{ repo_url }}:cent-ssh'
        memoryReservation: 40
        portMappings:
          - containerPort: 22
            hostPort: 0
            protocol: tcp
  - ecs_taskdefinition:
      profile: '{{ aws_profile }}'
      region: us-east-2
      network_mode: bridge
      family: ios-ansible-targets
      state: absent
      containers:
      - name: ssh-target
        image: '{{ repo_url }}:cisco-ios-sim'
        memoryReservation: 40
        portMappings:
          - containerPort: 22
            hostPort: 0
            protocol: tcp
  - cloudformation:
      template: ./cfn/ecs-static-size-cluster.yaml
      profile: '{{ aws_profile }}'
      region: us-east-2
      state: absent
      stack_name: static-ecs-cluster
      template_parameters:
        ParentVPCStack: scale-test-vpc
        SubnetsReach: Public
        InstanceType: c5.4xlarge
        SpotBidPrice: 0.20
        MaxSize: 8
        DesiredCapacity: 3
        MinSize: 0
        KeyName: '{{ key_name }}'
  - cloudformation:
      template: ./cfn/vpc-2azs.yaml
      state: absent
      stack_name: scale-test-vpc
      profile: '{{ aws_profile }}'
      region: us-east-2
      template_parameters:
        ClassB: 99
