---
- hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
  - vars.yml
  module_defaults:
    group/aws:
      profile: '{{ aws_profile }}'
      region: us-east-2
  tasks:
  - cloudformation:
      template: ./cfn/ecs-static-size-cluster.yaml
      stack_name: static-ecs-cluster
      template_parameters:
        ParentVPCStack: scale-test-vpc
        SubnetsReach: Public
        InstanceType: c5.4xlarge
        SpotBidPrice: 0.20
        MaxSize: 0
        DesiredCapacity: 0
        MinSize: 0
        KeyName: '{{ key_name }}'
